import { Connection, Keypair, PublicKey, SystemProgram, Transaction } from '@solana/web3.js';
import { Program, AnchorProvider, Wallet, BN } from '@coral-xyz/anchor';
import { TOKEN_PROGRAM_ID, getAssociatedTokenAddress, createAssociatedTokenAccountInstruction } from '@solana/spl-token';
import bs58 from 'bs58';
import * as dotenv from 'dotenv';

dotenv.config();

// =========================================================================
// PocketChange ($PCP) Flash Loan Executor
// =========================================================================
// Demonstrates how the backend Keeper Engine borrows from the $PCP Vault,
// performs a mocked external arbitrage block, and atomically repays.

const PRIVATE_KEY = process.env.PRIVATE_KEY;
if (!PRIVATE_KEY) throw new Error("Missing PRIVATE_KEY");

const RPC_URL = process.env.SOLANA_RPC_URL || "https://api.mainnet-beta.solana.com";
const connection = new Connection(RPC_URL, "confirmed");
const walletPair = Keypair.fromSecretKey(bs58.decode(PRIVATE_KEY));
const wallet = new Wallet(walletPair);
const provider = new AnchorProvider(connection, wallet, { commitment: "confirmed" });

// Load the Vault Program ID
const VAULT_PROGRAM_ID = new PublicKey("4yfwG2VqohXCMpX7SKz3uy7CKzujL4SkhjJMkgKvBAGS");

async function executeFlashLoanAtomicRoute() {
    console.log(`\n⚡ PocketChange Flash Loan Engine Initializing...`);
    console.log(`🔑 Keeper: ${wallet.publicKey.toBase58()}`);

    // --- Configuration ---
    // In production, this dynamic IDL loading would be generated by Anchor
    const idl = await Program.fetchIdl(VAULT_PROGRAM_ID, provider);
    if (!idl) throw new Error("Failed to fetch IDL from Mainnet!");
    
    // @ts-ignore - Dynamic IDL casting for the script
    const program = new Program(idl, VAULT_PROGRAM_ID, provider);

    // Derive the Vault State PDA constraint
    const [vaultStatePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("vault")],
        program.programId
    );
    console.log(`🏦 Target Vault PDA: ${vaultStatePda.toBase58()}`);

    // Fetch the Vault State to dynamically pull the Underlying Mint and Treasury setup
    const vaultState = await program.account.vaultState.fetch(vaultStatePda);
    const underlyingMint = vaultState.underlyingMint as PublicKey;
    const treasuryAccount = vaultState.treasury as PublicKey;

    // Resolve ATA for the Vault
    const vaultUnderlyingAta = await getAssociatedTokenAddress(
        underlyingMint,
        vaultStatePda,
        true
    );

    // Resolve ATA for the Keeper (Borrower)
    const keeperUnderlyingAta = await getAssociatedTokenAddress(
        underlyingMint,
        wallet.publicKey
    );

    // --- Arbitrage Execution Simulation ---
    const borrowAmount = new BN(1_000_000_000); // 1,000 $PCP (assume 6 decimals)
    const flashFeeBps = vaultState.flashFeeBps as number; // e.g., 15 bps
    const feeAmount = borrowAmount.muln(flashFeeBps).divn(10000);
    const repaymentAmount = borrowAmount.add(feeAmount);

    console.log(`💸 Flash Borrowing: ${borrowAmount.toString()} $PCP`);
    console.log(`📉 Required Repayment (+Fee): ${repaymentAmount.toString()} $PCP`);

    const tx = new Transaction();

    // 1. INSTRUCTION 1: Borrow
    const borrowIx = await program.methods
        .flashLoan(borrowAmount)
        .accounts({
            vaultState: vaultStatePda,
            vaultUnderlying: vaultUnderlyingAta,
            borrowerAccount: keeperUnderlyingAta,
            tokenProgram: TOKEN_PROGRAM_ID,
            // @ts-ignore
            instructions: new PublicKey("Sysvar1nstructions1111111111111111111111111")
        })
        .instruction();
    
    // 2. INSTRUCTION N: Arbitrage Route (Simulated logic here)
    // Here we would dynamically push Jupiter or Raydium Swap Instruction CPIs.
    // e.g., tx.add(jupiterSwapIx1 ); tx.add(jupiterSwapIx2);
    // Since we are validating the flash architecture, we assume the wallet already holds 
    // enough PCP to cover the fee for this simulation, omitting actual external swap APIs.

    // 3. INSTRUCTION N+1: Repay
    const repayIx = await program.methods
        .flashLoanRepay(borrowAmount, feeAmount)
        .accounts({
            vaultState: vaultStatePda,
            vaultUnderlying: vaultUnderlyingAta,
            treasuryAccount: treasuryAccount,
            borrowerAccount: keeperUnderlyingAta,
            borrower: wallet.publicKey,
            tokenProgram: TOKEN_PROGRAM_ID,
        })
        .instruction();

    // Assemble the atomic block. If repayIx isn't exactly appended, borrowIx reverts due to the Sysvar Introspection!
    tx.add(borrowIx);
    // tx.add(jupiterArbitrageIxs...)
    tx.add(repayIx);

    console.log("📝 Sending Atomic Transaction Block to Mainnet...");
    try {
        const sig = await provider.sendAndConfirm(tx, [walletPair], { skipPreflight: true });
        console.log(`✅ Flash Loan & Arbitrage Succeeded!`);
        console.log(`📜 TX: https://solscan.io/tx/${sig}`);
    } catch (e: any) {
        console.error("❌ Transaction Failed:");
        console.error(e.message || e);
    }
}

executeFlashLoanAtomicRoute().catch(console.error);
