import { Connection, Keypair, PublicKey } from '@solana/web3.js';
import bs58 from 'bs58';
import * as dotenv from 'dotenv';
import { BagsSDK } from '@bagsfm/bags-sdk';

dotenv.config();

// =========================================================================
// PocketChange ($PCP) Bags.fm Liquidity Pool Launch Integration
// =========================================================================

// ENV REQS:
// BAGS_API_KEY="bags_prod_..."
// PRIVATE_KEY="your_base58_private_key"
// SOLANA_RPC_URL="https://api.mainnet-beta.solana.com"

const PRIVATE_KEY = process.env.PRIVATE_KEY;
if (!PRIVATE_KEY) {
  throw new Error("Missing PRIVATE_KEY in .env");
}

const BAGS_API_KEY = process.env.BAGS_API_KEY as string;
if (!BAGS_API_KEY) {
  throw new Error("Missing BAGS_API_KEY in .env");
}
const RPC_URL = process.env.SOLANA_RPC_URL || "https://api.mainnet-beta.solana.com";

const connection = new Connection(RPC_URL, "confirmed");
const wallet = Keypair.fromSecretKey(bs58.decode(PRIVATE_KEY));

// ================= CONFIGURATION =================
// The Mint Address for existing $PCP Token
const PCP_MINT = new PublicKey("4yfwG2VqohXCMpX7SKz3uy7CKzujL4SkhjJMkgKvBAGS"); 

// The Metadata URL provided to the original launch or generated by TokenInfo
const PCP_METADATA_URL = "https://pcprotocol.dev/metadata.json"; // Update if hosted elsewhere

// The initial native buy amount wrapped in the launch payload
const INITIAL_BUY_LAMPORTS = 5_000_000_000; // E.g., 5 SOL 

async function main() {
    console.log("🚀 Initializing Bags.fm Launch SDK...");

    // 1. Initialize Bags Client
    const bags = new BagsSDK(BAGS_API_KEY, connection);
    console.log(`🔑 Connected via Wallet: ${wallet.publicKey.toBase58()}`);

    try {
        console.log(`📡 Requesting Bags.fm Launch Transaction for Mint: ${PCP_MINT.toBase58()}`);
        console.log(`💰 Generating Initial Buy Payload: ${INITIAL_BUY_LAMPORTS / 1e9} SOL`);

        // 2. We use the custom FeeShare / TokenLaunch services to hit their backend
        // Note: The sdk generates the `VersionedTransaction` representing the Meteora/Raydium pool injection orchestrated by Bags.fm
        const launchTx = await bags.tokenLaunch.createLaunchTransaction({
            metadataUrl: PCP_METADATA_URL,
            tokenMint: PCP_MINT,
            launchWallet: wallet.publicKey,
            initialBuyLamports: INITIAL_BUY_LAMPORTS,
            configKey: wallet.publicKey // Assuming standard config, or custom FeeShare config if defined
        });

        console.log("📝 Signing generated transaction payload...");
        
        // 3. Sign the transaction
        launchTx.sign([wallet]);

        console.log("📤 Broadcasting to Solana Mainnet-Beta...");
        
        // 4. Dispatch the signed bundle
        const signature = await connection.sendRawTransaction(launchTx.serialize(), {
            skipPreflight: true,
            maxRetries: 3
        });

        console.log(`✅ Bags.fm Liquidity Pool Injection Successful!`);
        console.log(`📜 Transaction Signature: https://solscan.io/tx/${signature}`);
        
    } catch (error) {
        console.error("❌ Bags SDK Execution Failed:");
        console.error(error);
    }
}

main().catch(console.error);
